name: CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"
      - "!renovate/**"
    tags:
      - "v**"

jobs:
  build:
    runs-on: ubuntu-latest

    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - run: corepack enable
      - run: corepack prepare --activate

      - run: yarn

      - run: yarn exec prettier --check ./

      - run: npx tsc

      - run: npm run build

      - run: |
          mkdir tmp
          cp -r dist tmp/dist
          cp package.json src ./tmp -r
        if: ${{ github.event_name == 'push' }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tmp
          user_name: "github-actions"
          user_email: "github-actions@github.com"
          enable_jekyll: false
